apiVersion : apps/v1
kind: Deployment
metadata:
  name: "airflowaks-3f3f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "airflowaks-3f3f"
  template:
    metadata:
      labels:
        app: "airflowaks-3f3f"
    spec:
      containers:
        - name: "airflowaks-3f3f"
          image: "gobesacr.azurecr.io/airflowaks"
          ports:
          - containerPort: 80